<?php include("includes/pageheader.php") ?>
  <div id="content_header">
    <h1>Introducing Concerto</h1>
    <br />
  </div>

  <div id="maincontent">
  <!-- main content begins here -->
<p>There's a new way to share events and information with others at Rensselaer Polytechnic Institute.  You're about to discover the simplicity, innovation, and effectiveness of Concerto, an Internet-based alternative to the high costs and limited appeal of traditional paper signs and banners that often flank campus thoroughfares.  If you're responsible for promoting talks, conferences, or other events to the Institute community, this guide will introduce you to how Concerto will make your life easier.  If you're interested in improving the effectiveness of communication between the various pieces of the RPI community, here you'll learn how Concerto brings benefits to the entire Institute through tighter information integration.  Welcome to campus advertising for the 21st century.</p>
<h1>Problem and Approach</h1>
<p>Campus organizations generally suffer from a lack of effective means of communicating with other parts of the Institute community.  Paper signage - banners and printed fliers - clutters up high-traffic corridors.  For maximum yield, event promoters often need to print hundreds of signs and spend time attaching them to walls and bulletin boards using tape, staples, and thumb tacks.  With the wind, weather, and regulations of traditional signing, the costs of these methods far outweigh the overall benefits.  Your organization may also be interested in using mass emails or the cable television network for notices.  Campus-wide emails are like banging in a nail with a sledgehammer - overkill that is unavailable to most people without special permission.  The cable television network provides a suitable outlet for promotion, but due to its nature does not allow direct moderation of submitted content by other stakeholders, such as students and staff members not responsible for maintenance of the entire system.  Concerto addresses all of these problems using an innovative, thoughtful approach.</p>
<p>The purpose of Concerto is to communicate events, announcements, and other information submitted by RPI organizations and individuals to the campus community through a variety of digital means.  This is primarily accomplished by presenting the events and announcements in a dynamic bulletin-board format on a large LCD screen.  Integration with existing services, such as dining halls and the Institute Events Calendar, is also dead simple - Concerto simply retrieves content from them.  The content submission system, accessible to all RPI community members with unique campus user accounts, is simply a web interface for uploading announcements and graphical materials to the system.  Content on each screen can be controlled by the people who are most directly connected to that display.  For instance, a display sponsored by the Lally School of Management and Technology can be moderated by Lally staff directly.</p>
<p>In recognition of the fact that different groups on different areas of campus have diverse interests, Concerto is designed to allow location-specific content.  Information tailored for a specific location is over other content for an individual screen.  Concerto on a display controlled by Sodexho Campus Services, for example, could show student announcements and relevant events and also prominently feature Sodexho-branded content, such as dining hall menus.  A display in the RPI Union would likely focus on the communication of club- and Union-related fliers and announcements.  And there are always other applications of location specificity for the system.  Imagine showing an estimated time of arrival for nearby shuttle buses on screens close to campus shuttle stops.</p>
<h1>Feeds: Your Own Little Content Buffet</h1>
<p>Feeds are the groups of content that you can choose from for your screen.  Think of each feed as a different food bar at your favorite buffet.  You've got huge helpings of information about Union clubs, an assortment of management and business colloquia, select notices from on-campus hospitality services, and a set of campus news updates to top it all off.  Sure, you could cram your plate full of lecture announcements, but you'll get more out of the meal if you choose from a variety of different offerings.</p>
<img src="images/feeds.jpg" alt="Feeds are sources of content for particular screens." />
<p>Each feed is formed to contain pieces of content that share a similar theme.  For example, events, meeting notices, and other advertisements from student clubs affiliated with the RPI Union will belong to a different feed from lectures and academic colloquia.  Those who control each hardware screen within the Concerto system will be able to subscribe their displays to as many feeds as they wish.  They can also choose to display content from each of those feeds more or less frequently than content on other feeds; this is called <b>weighting</b>.  The system will automatically figure out how frequently to pull content out of particular feeds based on the weights set by the people who control each hardware display through the control panel.</p>
<?php include("includes/pagefooter.php") ?>
